#! /bin/bash

NAME="yaluoye-celery"
APP_DIR=/home/dev/workspace/python/yaluoye
VENV_DIR=/opt/python-env/flask-env/

USER=dev
GROUP=dev

cd $VENV_DIR
source bin/activate

cd $APP_DIR

exec celery worker -A ca.tasks -P gevent -Q yaluoye.default --loglevel=INFO --logfile logs/celery_default.log



